### ISSUE TITLE
ImportError: No module named helper_files

### ISSUE THREAD

**Issue by rixon** [marcsantiago/CryptographyKit#1]
When trying to import as per the README.txt, importing returns an error:

```
>>> from Cryptokit.CaesarCipher import c_encipher, c_decipher, brute_force_decrypt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Cryptokit/CaesarCipher.py", line 6, in <module>
    from helper_files import detectEnglish
ImportError: No module named helper_files
```

**Comment by marcsantiago** [comment]
Hey sorry about that.  As you can see this hasn't been maintained.  However I just did a quick check.. If you downloaded it from zip, then it assumes thats your main python file is located in the same directory as the setup.py file.  

`> User-MacBook-Pro:CryptographyKit-master user$ `  `python c_cipher_utility.py --help`


alternatively you can install a package level version.  `python setup.py install` or `pip install CryptographyKit`
